apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::010373846865:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1UB0YIE312AKP
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::010373846865:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-02T17:19:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1521"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2bfbbd95-a4e9-4374-b579-9511f8cc1b1d
